In [1]:
import numpy as np
print(np.__version__)

1.19.0


### 1. Create a numpy array of size 10, filled with zeros

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 2. Create a numpy array with values ranging from 10 to 49

In [16]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### 3. Create a numpy matrix of 2*2 integers, filled with ones

In [25]:
np.ones([2, 2], dtype=int)

array([[1, 1],
       [1, 1]])

### 4. Create a numpy matrix of 3*2 float numbers, filled with ones

In [27]:
np.ones([3, 2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 5. Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones

In [32]:
x = np.array([[1, 2, 3],
            [4, 5, 6]])

y = np.ones(x.shape)
y

array([[1., 1., 1.],
       [1., 1., 1.]])

### 6. Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros

In [35]:
np.zeros(x.shape, dtype=x.dtype)

array([[0, 0, 0],
       [0, 0, 0]])

### Create a numpy matrix of 4*4 integers, filled with fives

In [37]:
np.ones(4)*5

array([5., 5., 5., 5.])

### 7. Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 8. Create a numpy array, filled with 3 random integer values between 1 and 10

In [91]:
print(np.random.randint(1, 10, size=5))
print(np.random.choice([3, 4, 5, 6], size=(3, 4)))

[7 1 8 6 9]
[[5 5 4 5]
 [3 5 5 6]
 [6 6 5 3]]


### 9. Create a 3 * 3 * 3 numpy matrix, filled with random float values

In [93]:
np.random.ranf(size=(3, 3, 3))

array([[[0.58260585, 0.91016826, 0.11670536],
        [0.89674437, 0.04613944, 0.09137473],
        [0.7346909 , 0.83936584, 0.5619615 ]],

       [[0.01656173, 0.1863315 , 0.97998938],
        [0.78432458, 0.88586448, 0.67232156],
        [0.61757746, 0.6973065 , 0.25932232]],

       [[0.23386277, 0.19479376, 0.69091998],
        [0.43380176, 0.69897464, 0.40460685],
        [0.44912314, 0.32785634, 0.77655766]]])

### 10. Given the X python list conver it to an Y numpy array

In [103]:
import sys
l = [1, 2, 3, 4, 5]
a = np.array(l)
a

array([1, 2, 3, 4, 5])

### 11. create the X numpy array, make a copy and store it on Y

In [104]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [106]:
y = np.copy(x)
y

array([[1, 2, 3],
       [4, 5, 6]])

### 12. Create a numpy array with numbers from 1 to 10

In [110]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 13. Create a numpy array with numbers from 1 to 10, in descending order

In [112]:
np.arange(start=10, stop=0, step=-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### 14. Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [128]:
z = np.arange(9).reshape(3,3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### 15. Show the memory size of the given Z numpy matrix

In [133]:
z.size*z.itemsize

72

### 16. Given the X numpy array, show its first element

In [135]:
z[0,0]

0

### 17. Given the X numpy array, show its last element

In [137]:
z[-1, -1]

8

In [138]:
z.size

9

### 18. Given the X numpy array, show all middle elements

In [153]:
p = np.full((3, 4), 0)
k=int(z.shape[0]/2)
z[k]

array([3, 4, 5])

### 19. Given the X numpy array, show the elements in reverse position

In [173]:
li = []
for n in reversed(z):
    for i in reversed(n):
        li.append(i)
        
print(f'memory of the list: {sys.getsizeof(li)}')
k = np.array(li)
print(f'memory of the array {k} is: {k.size*k.itemsize}')

memory of the list: 184
memory of the array [8 7 6 5 4 3 2 1 0] is: 72


### 20. Given the X numpy array, show the elements in an odd position

In [179]:
x = np.arange(10)
odd_list = np.arange(1, 10, 2)
print(x)
print(x[odd_list])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


## Array manipulation
### Convert the given integer numpy array to floar

In [185]:
x = np.arange(10)
np.array(x, dtype=float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### Reverse the given numpy array(first element becomes last)

In [214]:
x = np.arange(10)
print(np.flip(x))
x = x[::-1]
x

[9 8 7 6 5 4 3 2 1 0]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### sort the given numpy array

In [218]:
x = np.random.randint(1, 10, 10)
x

array([6, 6, 9, 5, 5, 1, 6, 6, 2, 6])

In [221]:
np.sort(x)

array([1, 2, 5, 5, 6, 6, 6, 6, 6, 9])

### Given the X numpy array, set the fifth element equal to 1

In [226]:
x = np.arange(0, 10)
x[4] = 1
x

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

### Given the x numpy array, get number equal to 2 or 10

In [231]:
x[((x == 2) | (x == 10))]

array([2])

### Given the x numpy array, return True if none of its elements is zero

In [237]:
len(x[x==0])>0

True