In [1]:
import numpy as np

In [23]:
# creating arrays from lists
my_list1 = [1, 2, 3, 4]
my_array = np.array(my_list1)
print(my_array)

[1 2 3 4]


In [29]:
my_list2 = [11, 22, 33, 44]

# merging 2 lists in an array
my_list = [my_list1, my_list2]

# This will create a 2x4 array
my_array = np.array(my_list)
print(my_array)

[[ 1  2  3  4]
 [11 22 33 44]]


In [31]:
print(f'shape of the arrays is: {my_array.shape}')
print(f'type of the arrays is: {my_array.dtype}')

shape of the arrays is: (2, 4)


In [9]:
my_list = [my_list1, my_list2]
print(my_list)

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [10]:
my_array = np.array(my_list)

In [11]:
my_array.shape

(2, 4)

In [12]:
my_array.dtype

dtype('int64')

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
my_zeros = np.zeros(5)
my_zeros.dtype

dtype('float64')

In [16]:
np.empty(5)

array([ 8.28848480e-317,  0.00000000e+000,  1.00979034e-316,
       -7.10373810e-205,  6.94767104e-310])

In [17]:
np.ones([5, 6])

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.arange(5) 
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])